Repository Project-Chirp/chirp-frontend, pull requests merged in 2023-05, with the labels that each got.

#32 T23: Account menu
  src/components/NavBar/AccountMenu.tsx
  src/components/NavBar/NavBar.tsx
Labels: feature

#34 T33: removed messages route from navbar and from the list of Protected Routes
  src/App.js
  src/components/NavBar/NavBar.tsx
Labels: tech debt

#37 T35: Redux
  package-lock.json
  package.json
  src/App.tsx
  src/components/NavBar/AccountMenu.tsx
  src/components/Posts/ComposePost.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostList.tsx
  src/context/PostContext.tsx
  src/context/UserContext.tsx
  src/index.js
  src/pages/Register.tsx
  src/state/hooks.ts
  src/state/slices/postSlice.ts
  src/state/slices/userSlice.ts
  src/state/store.ts
Labels: feature

#40 T29: Fix visual bug with post action numbers
  src/components/Posts/PostItem.tsx
Labels: bug
