Repository Project-Chirp/chirp-frontend, pull requests merged in 2023-07, with the labels that each got.

#51 T36: Reply modal
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/PostButtonModal.tsx
  src/components/Posts/ComposeReply.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/ExpandedPostReplies.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostList.tsx
  src/components/Posts/RepliesModal.tsx
  src/pages/ExpandedPost.tsx
  src/state/slices/expandedPostSlice.ts
  src/state/slices/postsSlice.ts
Labels: feature

#47 T44: Create message modal
  src/components/Messages/ConversationList.tsx
  src/components/Messages/CreateMessageModal/CreateMessageModal.tsx
  src/components/Messages/CreateMessageModal/MessagesModalList.tsx
  src/components/Messages/CreateMessageModal/MessagesModalListItem.tsx
  src/components/Messages/CreateMessageModal/MessagesSearchBar.tsx
  src/pages/DirectMessage.tsx
  src/pages/Messages.tsx
  src/state/slices/messagesSlice.ts
Labels: feature

#61 T58: Page layout template
  src/App.tsx
  src/components/Messages/ConversationList.tsx
  src/components/NavBar/NavBar.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/pages/DirectMessage.tsx
  src/pages/ExpandedPost.tsx
  src/pages/Layout.tsx
  src/pages/Messages.tsx
  src/pages/PageLoader.tsx
  src/pages/Profile.tsx
  src/pages/Register.tsx
  src/pages/Timeline.tsx
  src/pages/Welcome.tsx
  src/styles/App.css
Labels: feature, tech debt

#64 T56: Fix expanded post actions styling
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostList.tsx
Labels: bug, tech debt

#59 T46: Convert timestamps
  src/components/Messages/ConversationListItem.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/pages/DirectMessage.tsx
  src/utilities/formatTimestamp.ts
Labels: feature

#69 T68: Display reply and repost count
  src/components/Posts/ComposeReply.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/ExpandedPostReplies.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostList.tsx
  src/components/Profile/ProfileLikes.tsx
  src/components/Profile/ProfileReplies.tsx
  src/components/Profile/ProfileTweets.tsx
  src/pages/ExpandedPost.tsx
  src/pages/Profile.tsx
  src/state/slices/expandedPostSlice.ts
  src/state/slices/postsSlice.ts
  src/state/store.ts
  src/utilities/postUtilities.ts
Labels: feature, tech debt
