Repository Project-Chirp/chirp-frontend, pull requests merged in 2023-06, with the labels that each got.

#42 T16: Profile page
  package.json
  public/blue.jpg
  public/rock.jpg
  public/temp_banner.jpg
  src/components/Posts/ProfileLikes.tsx
  src/components/Posts/ProfileReplies.tsx
  src/components/Posts/ProfileTweets.tsx
  src/pages/Profile.tsx
  src/styles/Theme.tsx
Labels: feature

#43 T12: Messages list
  src/App.tsx
  src/components/Messages/MessagesList.tsx
  src/components/Messages/MessagesListItem.tsx
  src/components/Messages/SearchBar.tsx
  src/components/NavBar/NavBar.tsx
  src/pages/Messages.tsx
Labels: feature

#55 T50: Fixed the PostButtonModal and multiline posts
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/PostButtonModal.tsx
  src/components/Posts/ComposePost.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/pages/Timeline.tsx
  src/styles/Theme.tsx
Labels: bug, tech debt

#53 T52: Icon Colours
  src/components/NavBar/NavBar.tsx
  src/components/Posts/ComposePost.tsx
  src/components/Posts/ComposeReply.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/pages/Messages.tsx
  src/pages/Profile.tsx
  src/pages/Register.tsx
  src/styles/Theme.tsx
Labels: good first issue, tech debt

#54 T13: Direct message
  src/App.tsx
  src/components/Common/SearchBar.tsx
  src/components/Messages/ConversationList.tsx
  src/components/Messages/ConversationListItem.tsx
  src/components/Messages/MessagesList.tsx
  src/components/NavBar/AccountMenu.tsx
  src/components/NavBar/NavBar.tsx
  src/components/Posts/ComposePost.tsx
  src/components/Posts/ComposeReply.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/ExpandedPostReplies.tsx
  src/pages/DirectMessage.tsx
  src/pages/ExpandedPost.tsx
  src/pages/Messages.tsx
  src/pages/Timeline.tsx
  src/state/slices/expandedPostSlice.ts
  src/state/slices/messagesSlice.ts
  src/state/store.ts
  src/styles/Theme.tsx
Labels: feature
