Repository Project-Chirp/chirp-frontend, pull requests merged in 2024-09, with the labels that each got.

#118 T116, T117: Relevant user follow button bugs
  .github/pull_request_template.md
  src/components/Posts/ExpandedPostItem.tsx
  src/components/SideBar/RelevantUsers.tsx
  src/state/slices/postsSlice.ts
Labels: bug

#123 T106: Follower/Following list styling
  src/components/NavBar/AccountMenu.tsx
  src/components/Profile/EditProfileModal.tsx
  src/components/Profile/FollowListModal.tsx
  src/components/SideBar/SuggestedUsers.tsx
  src/pages/Profile.tsx
Labels: feature

#121 T120: Display full timestamp on hover
  src/components/Common/TooltipTimestamp.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/pages/DirectMessage.tsx
  src/utilities/formatTimestamp.ts
  src/utilities/formatTooltipTimestamp.tsx
Labels: enhancement

#114 T106: Follower/Following list modal
  src/components/NavBar/AccountMenu.tsx
  src/components/Profile/EditProfileModal.tsx
  src/components/Profile/FollowListModal.tsx
  src/components/SideBar/SuggestedUsers.tsx
  src/pages/Profile.tsx
Labels: feature

#119 T115: Edit posts
  src/components/Common/TooltipTimestamp.tsx
  src/components/Posts/EditPostModal.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostMenu.tsx
  src/state/slices/postsSlice.ts
  src/utilities/formatTimestamp.ts
Labels: feature

#125 T95, T124: Sharing posts, adding toasts
  src/App.tsx
  src/components/Common/Toast.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostDeleteConfirmationModal.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostMenu.tsx
  src/state/slices/postsSlice.ts
  src/state/slices/toastSlice.ts
  src/state/store.ts
Labels: feature
