Repository Project-Chirp/chirp-frontend, pull requests merged in 2024-10, with the labels that each got.

#126 T85: Search bar
  src/components/Common/SearchBarDropdown.tsx
  src/components/Messages/ConversationList.tsx
  src/components/SideBar/ExpandedPostSidebar.tsx
  src/components/SideBar/SideBar.tsx
Labels: feature

#130 T129: Fix edit post modal crash
  src/components/Posts/EditPostModal.tsx
  src/components/Posts/ExpandedPostItem.tsx
  src/components/Posts/PostItem.tsx
  src/components/Posts/PostMenu.tsx
Labels: bug

#133 T132: Update libraries
  package-lock.json
  package.json
  src/components/Auth/AuthProvider.tsx
  src/components/Common/SearchBar.tsx
  src/components/Common/SearchBarDropdown.tsx
  src/components/Messages/CreateMessageModal/MessagesSearchBar.tsx
  src/components/Profile/EditProfileModal.tsx
  src/pages/DirectMessage.tsx
  src/pages/Register.tsx
  src/styles/Theme.tsx
Labels: tech debt
