Repository Project-Chirp/chirp-frontend, pull requests merged in 2024-06, with the labels that each got.

#103 T102: Fix emoji picker overflow bug
  src/components/Common/EmojiPickerIconButton.tsx
  src/components/NavBar/PostButtonModal.tsx
  src/components/Posts/RepliesModal.tsx
Labels: bug

#104 T63: Navbar styling suggestions
  public/favicon.ico
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/logojade.png
  src/assets/logo.svg
  src/components/NavBar/AccountMenu.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavItem.tsx
  src/components/SideBar/Advertisement.tsx
  src/pages/Profile.tsx
  src/pages/Welcome.tsx
Labels: tech debt

#105 T71: Close post button modal after making a new post
  src/components/NavBar/NavBar.tsx
  src/components/Posts/ComposePost.tsx
Labels: bug, good first issue

#101 T63: Navbar styling
  public/favicon.ico
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/logojade.png
  src/assets/logo.svg
  src/components/NavBar/AccountMenu.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavItem.tsx
  src/components/SideBar/Advertisement.tsx
  src/pages/Profile.tsx
  src/pages/Welcome.tsx
Labels: tech debt
